version: '3.1'

services:

  stats-server:
    build: ./statistic-service
    container_name: ewm_stat_service_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me_stat
      - DB_USER=user1
      - DB_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore_with_me_stat
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./main-service
    container_name: ewm_main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore_with_me
      - DB_USER=user1
      - DB_PASSWORD=password
      - STATISTIC_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password
